import type { Metadata } from 'next'
import "@/src/styles/globals.css"
import { Inter as FontSans } from "next/font/google"
import {ThemeProvider} from "@/src/components/themeProvider";
import AppBarLayout from "@/src/modules/appBar/components/appBarLayout";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning className={fontSans.className}>
      <body className={"min-h-screen bg-background w-full font-sans antialiased"}>
      <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
      >
      <main className="min-h-screen w-full px-56">
          <AppBarLayout />
          {children}
      </main>
      </ThemeProvider>
      </body>
    </html>
  )
}
